Repository kubevela/kubevela, pull requests merged in 2022-05, with the labels that each got.

#3804 Fix: update latest version Fix: 1.2 upgrade 1.3 workflowstep XXX not found
  pkg/appfile/parser.go
  pkg/appfile/parser_test.go
  pkg/appfile/testdata/backport-1-2/app.yaml
  pkg/appfile/testdata/backport-1-2/apprev1.yaml
  pkg/appfile/testdata/backport-1-2/apprev2.yaml
  pkg/appfile/testdata/backport-1-2/apprev3.yaml
  pkg/appfile/testdata/backport-1-2/wsd.yaml
  pkg/controller/core.oam.dev/v1alpha2/application/revision.go
  pkg/controller/core.oam.dev/v1alpha2/application/revision_test.go
Labels: backport release-1.3

#3503 Fix: don't override user definied `region`
  pkg/appfile/appfile.go
  pkg/appfile/appfile_test.go
  pkg/cloudprovider/aliyun.go
  pkg/controller/core.oam.dev/v1alpha2/application/apply.go
  pkg/controller/core.oam.dev/v1alpha2/application/apply_test.go
  pkg/controller/core.oam.dev/v1alpha2/application/suite_test.go
  pkg/controller/core.oam.dev/v1alpha2/core/scopes/healthscope/healthscope.go
  pkg/utils/common/common.go
  references/cli/def.go
  references/cli/def_test.go
  test/e2e-addon-test/addon_test.go
Labels: backport release-1.3

#3835 Fix: The new addon can not shown in the Addons page
  pkg/addon/cache.go
  pkg/addon/cache_test.go
  pkg/addon/versioned_registry_test.go
  test/e2e-multicluster-test/suite_test.go
Labels: backport release-1.3

#3837 Fix: sensitive field of addon registry is exposed
  pkg/addon/source.go
  pkg/addon/source_test.go
  pkg/apiserver/rest/usecase/addon.go
Labels: backport release-1.3

#3827 Fix: resolve locally installed addons not being displayed
  references/cli/addon.go
  references/cli/addon_suite_test.go
  references/cli/addon_test.go
  references/cli/uninstall_test.go
Labels: backport release-1.3

#3839 Fix: add parse comments in lookupScript to make patch work
  pkg/cue/model/value/value.go
  pkg/cue/model/value/value_test.go
Labels: backport release-1.2, backport release-1.3

#3861 Fix: ignore no kind match error in gc
  pkg/resourcekeeper/cache.go
Labels: backport release-1.3

#3855 Feat: run image scan CI for every pull request and fix CVEs in time
  .github/workflows/codeql-analysis.yml
  .github/workflows/trivy-scan.yml
  go.mod
  go.sum
Labels: backport release-1.3

#3862 Fix: the endpoints is repeated and can not query the ingress with v1 version
  pkg/velaql/providers/query/collector.go
  pkg/velaql/providers/query/handler.go
  references/cli/addon.go
  references/cli/status.go
  references/cli/velaql.go
Labels: backport release-1.3

#3877 Fix: modify the template definition to solve the trait cli error
  charts/vela-core/templates/defwithtemplate/command.yaml
  charts/vela-core/templates/defwithtemplate/container-image.yaml
  charts/vela-core/templates/defwithtemplate/env.yaml
  charts/vela-minimal/templates/defwithtemplate/command.yaml
  charts/vela-minimal/templates/defwithtemplate/container-image.yaml
  charts/vela-minimal/templates/defwithtemplate/env.yaml
  pkg/controller/core.oam.dev/v1alpha2/application/application_controller_test.go
  references/cli/traits_test.go
  vela-templates/definitions/internal/trait/command.cue
  vela-templates/definitions/internal/trait/container-image.cue
  vela-templates/definitions/internal/trait/env.cue
Labels: backport release-1.3

#3939 Fix: remove last-applied-config annotation for configmap and secret
  pkg/oam/labels.go
  pkg/utils/apply/apply.go
  pkg/utils/apply/apply_test.go
Labels: backport release-1.3

#3928 Fix: addon compare vela version failure
  go.mod
  pkg/addon/addon.go
  pkg/addon/addon_test.go
  pkg/addon/example-1.0.1.tgz
Labels: backport release-1.3

#3968 Feat: mechanism to let user add relationship mapping rule by configmap
  pkg/oam/labels.go
  pkg/velaql/providers/query/handler.go
  pkg/velaql/providers/query/handler_test.go
  pkg/velaql/providers/query/tree.go
  pkg/velaql/providers/query/tree_test.go
Labels: backport release-1.4

#3984 Fix: initialize kube config multiple times
  cmd/apiserver/main.go
  pkg/apiserver/domain/service/project.go
  pkg/apiserver/domain/service/project_test.go
  pkg/apiserver/domain/service/rbac.go
  pkg/apiserver/domain/service/velaql.go
  pkg/apiserver/infrastructure/clients/kubeclient.go
  pkg/apiserver/server.go
  pkg/velaql/providers/query/types/health_status.go
  test/e2e-apiserver-test/suite_test.go
Labels: backport release-1.4

#3989 Fix: don't update version file when publish alpha/beta version
  .github/workflows/release.yml
Labels: backport release-1.4

#3981 Fix: delete Project fail
  pkg/apiserver/domain/service/config.go
Labels: backport release-1.4

#3988 Fix: add Target fail by fetch terraform-provider error
  pkg/apiserver/domain/service/project.go
Labels: backport release-1.4

#3985 Feat: support impersonation for application in apiserver
  charts/vela-core/templates/rbac/x-definition.yaml
  cmd/apiserver/main.go
  pkg/apiserver/domain/service/rbac.go
  pkg/apiserver/domain/service/target.go
  pkg/apiserver/infrastructure/clients/kubeclient.go
  pkg/apiserver/server.go
  pkg/apiserver/utils/auth.go
  pkg/apiserver/utils/context.go
  pkg/auth/privileges.go
  pkg/features/apiserver_features.go
Labels: backport release-1.4

#3986 Feat: upgrade cluster-gateway version
  charts/vela-core/README.md
  charts/vela-core/templates/cluster-gateway/cluster-gateway.yaml
  charts/vela-core/values.yaml
  charts/vela-minimal/README.md
  charts/vela-minimal/templates/cluster-gateway.yaml
  charts/vela-minimal/values.yaml
  go.mod
  go.sum
  test/e2e-multicluster-test/multicluster_test.go
Labels: backport release-1.4

#3998 Fix: add some default permissions about the configuration
  pkg/apiserver/domain/service/rbac.go
  pkg/apiserver/domain/service/rbac_test.go
  pkg/apiserver/interfaces/api/config.go
  pkg/apiserver/interfaces/api/project.go
Labels: backport release-1.4

#4001 Fix: optimized the version comparison
  pkg/addon/addon.go
  pkg/addon/addon_test.go
Labels: backport release-1.4

#4003 Feat: optimize some logic of topology resource-tree
  go.mod
  go.sum
  pkg/velaql/providers/query/handler.go
  pkg/velaql/providers/query/tree.go
  pkg/velaql/providers/query/tree_test.go
  pkg/velaql/providers/query/types/type.go
Labels: backport release-1.4

#4012 Fix: fail to query the count with MongoDB
  pkg/apiserver/infrastructure/datastore/mongodb/mongodb.go
  pkg/apiserver/infrastructure/datastore/mongodb/mongodb_test.go
Labels: backport release-1.4

#3975 Fix: step group documentation update and bug fix of firstExecuteTime mission
  docs/examples/workflow/step-group/README.md
  docs/examples/workflow/step-group/example.yaml
  pkg/workflow/workflow.go
Labels: backport release-1.4

#3992 Feat: enhance controller auth by removing useless features & add authentication for componentrevision+healthcheck
  apis/core.oam.dev/v1alpha1/envbinding_types.go
  apis/types/types.go
  charts/vela-core/templates/cluster-gateway/cluster-gateway.yaml
  charts/vela-core/templates/kubevela-controller.yaml
  charts/vela-core/templates/rbac/x-definition.yaml
  charts/vela-minimal/templates/cluster-gateway.yaml
  charts/vela-minimal/templates/kubevela-controller.yaml
  cmd/core/main.go
  e2e/application/application_test.go
  pkg/auth/round_trippers.go
  pkg/auth/round_trippers_test.go
  pkg/controller/core.oam.dev/v1alpha2/application/generator.go
  pkg/controller/core.oam.dev/v1alpha2/application/revision.go
  pkg/features/controller_features.go
  pkg/resourcekeeper/componentrevision.go
  pkg/resourcekeeper/gc.go
  pkg/webhook/core.oam.dev/v1alpha2/application/mutating_handler.go
  pkg/webhook/core.oam.dev/v1alpha2/application/mutating_handler_test.go
  pkg/workflow/providers/multicluster/deploy.go
  test/e2e-multicluster-test/multicluster_test.go
  test/e2e-test/application_test.go
Labels: backport release-1.4

#4011 Fix: VelaQL fail to parse query result to json format
  pkg/cue/utils.go
  pkg/cue/utils_test.go
  pkg/velaql/providers/query/handler.go
  pkg/velaql/providers/query/utils.go
  pkg/velaql/providers/query/utils_test.go
  pkg/workflow/providers/kube/handle.go
  references/cli/velaql_test.go
  test/e2e-apiserver-test/testdata/component-pod-view.yaml
Labels: backport release-1.4

#4013 Fix: unknown field ignoreTerraformComponent
  pkg/workflow/step/types.go
Labels: backport release-1.4

#4007 Fix: vela port-forward not working for webservice component
  references/cli/portforward.go
  references/cli/portforward_test.go
Labels: backport release-1.4

#3973 Feat: add affinity trait to merge node and pod affinity
  charts/vela-core/templates/defwithtemplate/affinity.yaml
  charts/vela-core/templates/defwithtemplate/node-affinity.yaml
  charts/vela-minimal/templates/defwithtemplate/affinity.yaml
  docs/examples/traits/affinity/example.yaml
  pkg/controller/core.oam.dev/v1alpha2/application/application_controller_test.go
  vela-templates/definitions/deprecated/node-affinity.cue
  vela-templates/definitions/internal/trait/affinity.cue
Labels: backport release-1.4

#4026 Feat: add the creating and deleting permission APIs
  docs/apidoc/swagger.json
  pkg/apiserver/domain/repository/grpc.go
  pkg/apiserver/domain/service/rbac.go
  pkg/apiserver/domain/service/rbac_test.go
  pkg/apiserver/interfaces/api/assembler/v1/do2dto.go
  pkg/apiserver/interfaces/api/dto/v1/types.go
  pkg/apiserver/interfaces/api/env.go
  pkg/apiserver/interfaces/api/project.go
  pkg/apiserver/interfaces/api/rbac.go
  pkg/apiserver/utils/bcode/015_rbac.go
Labels: backport release-1.4

#4038 Fix: env trait error when existing env exists
  charts/vela-core/templates/defwithtemplate/env.yaml
  charts/vela-minimal/templates/defwithtemplate/env.yaml
  vela-templates/definitions/internal/trait/env.cue
Labels: backport release-1.3, backport release-1.4

#3941 Feat: add if in workflow
  apis/core.oam.dev/common/types.go
  charts/vela-core/README.md
  charts/vela-core/crds/core.oam.dev_applicationrevisions.yaml
  charts/vela-core/crds/core.oam.dev_applications.yaml
  charts/vela-core/crds/core.oam.dev_workflows.yaml
  charts/vela-core/templates/kubevela-controller.yaml
  charts/vela-core/values.yaml
  charts/vela-minimal/README.md
  charts/vela-minimal/crds/core.oam.dev_applicationrevisions.yaml
  charts/vela-minimal/crds/core.oam.dev_applications.yaml
  charts/vela-minimal/templates/kubevela-controller.yaml
  charts/vela-minimal/values.yaml
  legacy/charts/vela-core-legacy/crds/core.oam.dev_applicationrevisions.yaml
  legacy/charts/vela-core-legacy/crds/core.oam.dev_applications.yaml
  legacy/charts/vela-core-legacy/crds/core.oam.dev_workflows.yaml
  pkg/apiserver/domain/service/workflow.go
  pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go
  pkg/controller/core.oam.dev/v1alpha2/application/application_controller_test.go
  pkg/controller/core.oam.dev/v1alpha2/application/generator.go
  pkg/features/controller_features.go
  pkg/workflow/hooks/data_passing.go
  pkg/workflow/hooks/data_passing_test.go
  pkg/workflow/tasks/custom/task.go
  pkg/workflow/tasks/custom/task_test.go
  pkg/workflow/tasks/discover.go
  pkg/workflow/tasks/discover_test.go
  pkg/workflow/types/types.go
  pkg/workflow/workflow.go
  pkg/workflow/workflow_test.go
  references/cli/workflow.go
  test/e2e-test/application_test.go
Labels: backport release-1.4

#4056 Fix: Fail to get the endpoints via the VelaQL
  pkg/velaql/providers/query/handler.go
Labels: backport release-1.4

#4057 Fix: the policies can not be deleted
  pkg/apiserver/domain/repository/application.go
  pkg/apiserver/domain/service/application.go
  pkg/apiserver/domain/service/envbinding.go
  pkg/apiserver/domain/service/envbinding_test.go
  pkg/apiserver/interfaces/api/application.go
Labels: backport release-1.4

#4060 Fix: set workflow to finish before record in controller revision
  pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go
Labels: backport release-1.4

#4061 Fix: CI workflow for rollout acr image build and push
  .github/workflows/registry.yml
Labels: backport release-1.4

#4059 Fix: remove the tcp protocol prefix in the endpoint string
  pkg/velaql/providers/query/handler_test.go
  pkg/velaql/providers/query/types/type.go
  references/cli/velaql_test.go
Labels: backport release-1.4

#4070 Fix: Can not delete terraform provider
  pkg/utils/config/application.go
Labels: backport release-1.4

#4072 Fix: upgrade from v1.3+ to v1.4+ with new secret for cluster-gateway
  charts/vela-core/templates/cluster-gateway/certmanager.yaml
  charts/vela-core/templates/cluster-gateway/cluster-gateway.yaml
  charts/vela-core/templates/cluster-gateway/job-patch.yaml
Labels: backport release-1.4

#3519 Feat: build the query capability of VelaQL into vela-cli
  e2e/application/application_test.go
  e2e/application/component-pod-view.yaml
  references/cli/cli.go
  references/cli/velaql.go
Labels: backport release-1.4

#4055 Fix: Improve vela provider add response
  references/cli/provider.go
  references/cmd/cli/main.go
Labels: backport release-1.4

#4075 Fix: change the region to customRegion
  pkg/apiserver/domain/repository/workflow.go
Labels: backport release-1.4

#4073 Chore: hide some definitions in VelaUX
  charts/vela-core/templates/defwithtemplate/container-image.yaml
  charts/vela-core/templates/defwithtemplate/deploy2env.yaml
  charts/vela-core/templates/defwithtemplate/json-merge-patch.yaml
  charts/vela-core/templates/defwithtemplate/json-patch.yaml
  charts/vela-core/templates/defwithtemplate/ref-objects.yaml
  charts/vela-core/templates/defwithtemplate/step-group.yaml
  charts/vela-minimal/templates/defwithtemplate/container-image.yaml
  charts/vela-minimal/templates/defwithtemplate/json-merge-patch.yaml
  charts/vela-minimal/templates/defwithtemplate/json-patch.yaml
  charts/vela-minimal/templates/defwithtemplate/ref-objects.yaml
  charts/vela-minimal/templates/defwithtemplate/step-group.yaml
  vela-templates/definitions/internal/component/ref-objects.cue
  vela-templates/definitions/internal/trait/container-image.cue
  vela-templates/definitions/internal/trait/json-merge-patch.cue
  vela-templates/definitions/internal/trait/json-patch.cue
  vela-templates/definitions/internal/workflowstep/deploy2env.cue
  vela-templates/definitions/internal/workflowstep/step-group.cue
Labels: backport release-1.4

#4081 Fix(addon): more note info and filter prerelease addon version
  pkg/addon/versioned_registry.go
  pkg/addon/versioned_registry_test.go
  references/cli/addon.go
Labels: backport release-1.4
