Repository kubevela/kubevela, pull requests merged in 2022-09, with the labels that each got.

#4673 Chore: Add v1.23 to regular CI test
  .github/workflows/apiserver-test.yaml
  .github/workflows/e2e-multicluster-test.yml
  .github/workflows/e2e-rollout-test.yml
  .github/workflows/e2e-test.yml
  test/e2e-multicluster-test/multicluster_standalone_test.go
Labels: backport release-1.5

#4684 Fix: enabling addon cannot update definition bug
  pkg/addon/addon_suite_test.go
  pkg/addon/utils.go
Labels: backport release-1.5

#4687 Feat: request token when vela auth gen-kubeconfig
  .github/workflows/apiserver-test.yaml
  .github/workflows/e2e-multicluster-test.yml
  .github/workflows/e2e-rollout-test.yml
  .github/workflows/e2e-test.yml
  pkg/auth/kubeconfig.go
  test/e2e-multicluster-test/multicluster_test.go
  test/e2e-multicluster-test/suite_test.go
Labels: backport release-1.5

#4696 Feat: add nodeport in webservice
  charts/vela-core/templates/defwithtemplate/webservice.yaml
  charts/vela-minimal/templates/defwithtemplate/webservice.yaml
  vela-templates/definitions/internal/component/webservice.cue
Labels: backport release-1.5

#4709 Fix: resolve an issue where uninstallation continues even if user says no
  references/cli/uninstall.go
  references/cli/uninstall_test.go
Labels: backport release-1.3, backport release-1.4, backport release-1.5

#4721 Fix: CVE-2022-27664
  go.mod
  go.sum
Labels: backport release-1.4, backport release-1.5

#4718 Fix: the workflow records do not delete if the driver is MongoDB
  pkg/apiserver/domain/model/workflow.go
  pkg/apiserver/domain/service/workflow.go
  pkg/apiserver/domain/service/workflow_test.go
Labels: backport release-1.5

#4706 Fix: vela show panic for component markdown format
  e2e/commonContext.go
  e2e/trait/trait_test.go
  e2e/workload/workload_test.go
  references/cli/show.go
Labels: backport release-1.5

#4731 Feat: fix empty cluster topology and support select non-control-plane clusters
  go.mod
  go.sum
  pkg/policy/topology.go
  pkg/policy/topology_test.go
  references/docgen/cluster_test.go
Labels: backport release-1.5

#4729 Fix: wrong endpoint for LoadBalancer type service
  pkg/velaql/providers/query/endpoint.go
  pkg/velaql/providers/query/endpoint_test.go
  pkg/velaql/providers/query/handler_test.go
  pkg/velaql/providers/query/types/type.go
  references/cli/velaql_test.go
Labels: backport release-1.5

#4714 Fix: query the resource duplicately
  pkg/velaql/providers/query/collector.go
  pkg/velaql/providers/query/endpoint.go
  pkg/velaql/providers/query/handler.go
  pkg/velaql/providers/query/utils.go
  references/cli/top/model/resource.go
  test/e2e-apiserver-test/velaql_test.go
Labels: backport release-1.5

#4745 Fix: panic when properties empty
  pkg/workflow/step/generator.go
Labels: backport release-1.4, backport release-1.5

#4763 Fix: rollout privileges lack in controller
  charts/vela-core/templates/kubevela-controller.yaml
  charts/vela-minimal/templates/kubevela-controller.yaml
Labels: backport release-1.5

#4769 Fix: gc legacy rt with regularization
  pkg/resourcekeeper/gc.go
  pkg/resourcekeeper/gc_suite_test.go
  pkg/resourcekeeper/utils.go
  pkg/utils/k8s.go
  pkg/utils/k8s_test.go
Labels: backport release-1.4, backport release-1.5

#4773 Fix: memory leak of the apiserver
  cmd/apiserver/main.go
  cmd/core/main.go
  pkg/apiserver/config/config.go
  pkg/apiserver/event/sync/worker.go
  pkg/utils/pprof.go
Labels: backport release-1.5

#4778 Fix: allow to read definition from user's namespace when force delete
  references/common/application.go
  references/common/application_test.go
Labels: backport release-1.4, backport release-1.5

#4796 Fix: it does not check the same name for 'vela env init'
  pkg/utils/env/env.go
Labels: backport release-1.5

#4799 Fix: add path clean for request
  pkg/utils/common/common.go
Labels: backport release-1.5

#4801 Feat: add port name to CollectServiceEndpoints
  pkg/stdlib/pkgs/query.cue
  pkg/velaql/providers/query/endpoint.go
  pkg/velaql/providers/query/endpoint_test.go
  pkg/velaql/providers/query/handler.go
  pkg/velaql/providers/query/handler_test.go
  pkg/velaql/providers/query/types/type.go
Labels: backport release-1.5

#4809 Feat: add image-pull-policy to init-container
  charts/vela-core/templates/defwithtemplate/init-container.yaml
  charts/vela-minimal/templates/defwithtemplate/init-container.yaml
  vela-templates/definitions/internal/trait/init-container.cue
Labels: backport release-1.5

#4808 Feat: workflow will rerun when application workflow changes
  pkg/controller/core.oam.dev/v1alpha2/application/revision.go
  test/e2e-multicluster-test/multicluster_test.go
  test/e2e-multicluster-test/testdata/app/app-lite-with-workflow.yaml
Labels: backport release-1.5
