Repository kubevela/kubevela, pull requests merged in 2022-08, with the labels that each got.

#4512 Fix: missing return when token is null
  pkg/apiserver/interfaces/api/authentication.go
Labels: backport release-1.4, backport release-1.5

#4511 Fix: there is no color in the diff report
  cmd/apiserver/main.go
Labels: backport release-1.5

#4517 Fix: can not find the resource when the resource namespace is different with application
  references/cli/portforward.go
Labels: backport release-1.5

#4496 Fix: empty health policy do not check object existence
  pkg/appfile/appfile.go
  pkg/cue/definition/template.go
  test/e2e-multicluster-test/multicluster_test.go
  test/e2e-multicluster-test/testdata/app/app-bad-resource.yaml
Labels: backport release-1.5

#4521 Fix: fix e2e flaky tests
  e2e/addon/mock/utils/utils.go
  makefiles/e2e.mk
Labels: backport release-1.5

#4516 Feat: add http status and code from http cmd run
  pkg/builtin/http/http.go
  pkg/workflow/providers/http/do_test.go
Labels: backport release-1.5

#4525 Feat: add the daemonset resource rule for building the tree
  pkg/velaql/providers/query/collector.go
  pkg/velaql/providers/query/tree.go
  pkg/velaql/providers/query/tree_test.go
Labels: backport release-1.5

#4523 Fix: storage patch env
  pkg/cue/model/sets/operation.go
  pkg/cue/model/sets/operation_test.go
  test/e2e-multicluster-test/multicluster_test.go
  test/e2e-multicluster-test/testdata/app/app-with-env-and-storage.yaml
Labels: backport release-1.5

#4535 Fix: publish chart version
  .github/workflows/chart.yaml
Labels: backport release-1.5

#4530 Feat: support change resource gc policy from onAppUpdate to Never
  apis/core.oam.dev/v1alpha1/garbagecollect_types.go
  apis/core.oam.dev/v1beta1/resourcetracker_types.go
  apis/core.oam.dev/v1beta1/resourcetracker_types_test.go
  charts/vela-core/crds/core.oam.dev_resourcetrackers.yaml
  charts/vela-minimal/crds/core.oam.dev_resourcetrackers.yaml
  legacy/charts/vela-core-legacy/crds/core.oam.dev_resourcetrackers.yaml
  pkg/resourcekeeper/componentrevision.go
  pkg/resourcekeeper/delete.go
  pkg/resourcekeeper/dispatch.go
  pkg/resourcekeeper/dispatch_and_delete_test.go
  pkg/resourcekeeper/gc.go
  pkg/resourcekeeper/gc_suite_test.go
  pkg/resourcekeeper/gc_test.go
  pkg/resourcekeeper/options.go
  pkg/resourcekeeper/options_test.go
  pkg/resourcetracker/app.go
  pkg/resourcetracker/app_test.go
  test/e2e-multicluster-test/multicluster_test.go
  test/e2e-multicluster-test/testdata/app/app-gc-policy-change.yaml
Labels: backport release-1.5

#4531 Feat: Check def binding to a component
  e2e/addon/mock/testdata/mock-addon/definitions/json-patch.cue
  e2e/addon/mock/testdata/mock-addon/readme.md
  pkg/addon/addon.go
  pkg/addon/utils.go
  pkg/addon/utils_test.go
  pkg/addon/versioned_registry.go
  pkg/apiserver/domain/service/addon.go
  pkg/oam/labels.go
  test/e2e-apiserver-test/addon_test.go
Labels: backport release-1.5

#4541 Fix: sidecar trait
  charts/vela-core/templates/defwithtemplate/sidecar.yaml
  charts/vela-minimal/templates/defwithtemplate/sidecar.yaml
  vela-templates/definitions/internal/trait/sidecar.cue
Labels: backport release-1.5

#4545 Feat: report the manifest name when addon enabling failed
  pkg/addon/addon.go
  pkg/addon/render.go
  pkg/addon/utils.go
Labels: backport release-1.5

#4546 Fix: remove the cloudshell dockerfile
  .github/workflows/registry.yml
  Dockerfile.cloudshell
  charts/vela-core/templates/velaql/component-pod.yaml
  charts/vela-core/templates/velaql/component-service.yaml
Labels: backport release-1.5

#4550 Chore: fix cli description to remove html tag format
  references/cli/def.go
  references/cli/dryrun.go
  references/cli/velaql.go
Labels: backport release-1.5

#4553 Feat: ignore control check for resource from aggregate apiserver without resource version
  pkg/utils/apply/apply.go
  pkg/utils/apply/apply_test.go
Labels: backport release-1.5

#4559 Fix: compare resource without version
  apis/core.oam.dev/v1beta1/resourcetracker_types.go
  apis/core.oam.dev/v1beta1/resourcetracker_types_test.go
Labels: backport release-1.5

#4561 Fix: vela CLI provider compatibility
  pkg/apiserver/domain/service/config.go
  pkg/apiserver/domain/service/config_test.go
  pkg/apiserver/domain/service/tags.go
  pkg/apiserver/domain/service/tags_test.go
  pkg/definition/definition.go
  references/cli/provider.go
  references/cli/provider_test.go
Labels: backport release-1.5

#4563 Fix: reject applications with empty policy properties
  pkg/appfile/parser.go
  pkg/appfile/parser_test.go
  pkg/webhook/core.oam.dev/v1alpha2/application/validating_handler.go
  pkg/webhook/core.oam.dev/v1alpha2/application/validating_handler_test.go
  pkg/webhook/core.oam.dev/v1alpha2/applicationconfiguration/validating_handler.go
Labels: backport release-1.4, backport release-1.5

#4571 Fix: fix addon bond component annotaion
  pkg/addon/utils.go
  pkg/addon/utils_test.go
  pkg/oam/labels.go
Labels: backport release-1.5

#4507 Fix: Vela CLI 纳管集群后，无法通过APi接口对该集群创建namespace #4421
  pkg/apiserver/domain/service/cluster.go
Labels: backport release-1.5

#4572 Docs: add description for shared-resource
  charts/vela-core/templates/defwithtemplate/shared-resource.yaml
  charts/vela-minimal/templates/defwithtemplate/shared-resource.yaml
  references/docgen/def-doc/policy/shared-resource.eg.md
  vela-templates/definitions/internal/policy/shared-resource.cue
Labels: backport release-1.5

#4573 Feat: definition support controller requirement
  cmd/core/main.go
  pkg/controller/core.oam.dev/oamruntime_controller.go
  pkg/controller/core.oam.dev/v1alpha2/core/components/componentdefinition/componentdefinition_controller.go
  pkg/controller/core.oam.dev/v1alpha2/core/components/componentdefinition/componentdefinition_suit_test.go
  pkg/controller/core.oam.dev/v1alpha2/core/traits/traitdefinition/traitdefinition_controller.go
  pkg/controller/core.oam.dev/v1alpha2/core/traits/traitdefinition/traitdefinition_suite_test.go
  pkg/controller/core.oam.dev/v1alpha2/core/workflow/workflowstepdefinition/suite_test.go
  pkg/controller/core.oam.dev/v1alpha2/core/workflow/workflowstepdefinition/workflowstepdefinition_controller.go
  pkg/oam/labels.go
Labels: backport release-1.3, backport release-1.4, backport release-1.5

#4580 Fix: add status code for cue struct
  pkg/stdlib/pkgs/http.cue
Labels: backport release-1.5

#4583 Fix: gc resource without resourceversion
  pkg/resourcekeeper/cache.go
  pkg/resourcekeeper/cache_test.go
Labels: backport release-1.5

#4587 Fix: fix writing logs to file
  cmd/core/main.go
Labels: backport release-1.4, backport release-1.5

#4593 Fix: try to fix addon flaky test
  e2e/addon/mock/utils/utils.go
  e2e/addon/mock/vela_addon_mock_server.go
  test/e2e-apiserver-test/addon_test.go
Labels: backport release-1.5

#4595 Feat: align resource selector across policies
  apis/core.oam.dev/v1alpha1/applyonce_types.go
  apis/core.oam.dev/v1alpha1/garbagecollect_types.go
  pkg/resourcekeeper/statekeep_suite_test.go
Labels: backport release-1.5

#4604 Fix: the create time of the synced policies is zero
  pkg/apiserver/event/sync/store.go
  pkg/apiserver/event/sync/worker_test.go
  pkg/apiserver/infrastructure/datastore/kubeapi/kubeapi_test.go
  references/cli/addon.go
Labels: backport release-1.5

#4616 Fix: skipGC remove labels for multi-cluster resource not use correct ctx
  pkg/resourcekeeper/gc.go
Labels: backport release-1.5

#4626 Fix: up command example
  references/cli/kube.go
  references/cli/up.go
Labels: backport release-1.5

#4638 Fix: optimize workflow debug cmd
  references/cli/debug.go
  references/cli/debug_test.go
Labels: backport release-1.4, backport release-1.5

#4634 Fix: fix signedKey using platform id
  pkg/apiserver/domain/model/system_info.go
  pkg/apiserver/domain/service/authentication.go
  pkg/apiserver/domain/service/system_info.go
Labels: backport release-1.4, backport release-1.5

#4645 Fix: add supported but missing provider
  references/cli/def.go
Labels: backport release-1.4, backport release-1.5

#4670 Fix: unknown field cluster
  charts/vela-core/templates/defwithtemplate/topology.yaml
  charts/vela-minimal/templates/defwithtemplate/topology.yaml
  vela-templates/definitions/internal/policy/topology.cue
Labels: backport release-1.5
