Repository kubevela/kubevela, pull requests merged in 2022-07, with the labels that each got.

#4297 Fix: kube apply ignore userinfo for rt
  pkg/auth/userinfo.go
  pkg/resourcekeeper/dispatch.go
Labels: backport release-1.4

#4298 Fix: fix the goroutine leak in CUE when use http request
  pkg/builtin/http/http.go
Labels: backport release-1.2, backport release-1.3, backport release-1.4

#4305 Fix: fail to query the application logs with the special characters
  pkg/apiserver/domain/service/velaql.go
  pkg/stdlib/pkgs/query.cue
  pkg/velaql/providers/query/handler.go
Labels: backport release-1.4

#4337 Fix: disable apprev status update when apprev disabled
  pkg/controller/core.oam.dev/v1alpha2/application/revision.go
Labels: backport release-1.4

#4341 Fix: enhance sidecar & init traits
  charts/vela-core/templates/defwithtemplate/init-container.yaml
  charts/vela-core/templates/defwithtemplate/service-account.yaml
  charts/vela-core/templates/defwithtemplate/sidecar.yaml
  charts/vela-minimal/templates/defwithtemplate/init-container.yaml
  charts/vela-minimal/templates/defwithtemplate/service-account.yaml
  charts/vela-minimal/templates/defwithtemplate/sidecar.yaml
  vela-templates/definitions/internal/trait/init-container.cue
  vela-templates/definitions/internal/trait/service-account.cue
  vela-templates/definitions/internal/trait/sidecar.cue
Labels: backport release-1.4

#4349 Fix: health check use original ns if no override and original exists
  pkg/appfile/appfile.go
  pkg/controller/core.oam.dev/v1alpha2/application/apply.go
  pkg/controller/core.oam.dev/v1alpha2/core/scopes/healthscope/healthscope.go
  pkg/cue/definition/template.go
  pkg/oam/util/helper.go
Labels: backport release-1.4

#4351 Fix: init container bug
  charts/vela-core/templates/defwithtemplate/init-container.yaml
  charts/vela-minimal/templates/defwithtemplate/init-container.yaml
  vela-templates/definitions/internal/trait/init-container.cue
Labels: backport release-1.4

#4345 Feat: optimize imports packages to reduce 75% cpu with better performance
  pkg/cue/model/value/value_test.go
  pkg/stdlib/packages.go
  pkg/stdlib/packages_test.go
  pkg/workflow/tasks/custom/task.go
Labels: backport release-1.4

#4360 Fix: add the job of independently publishing chart packages
  .github/workflows/chart.yaml
  .github/workflows/registry.yml
Labels: backport release-1.4

#4367 Fix: several minor bugs
  pkg/controller/core.oam.dev/v1alpha2/application/generator.go
  pkg/resourcetracker/app.go
  pkg/stdlib/pkgs/kube.cue
  pkg/workflow/providers/kube/handle.go
Labels: backport release-1.4

#4363 Fix: fail directly when app terminated
  references/cli/addon.go
Labels: backport release-1.4

#4384 Fix: add usage comment for ref-objects
  charts/vela-core/templates/defwithtemplate/ref-objects.yaml
  charts/vela-minimal/templates/defwithtemplate/ref-objects.yaml
  vela-templates/definitions/internal/component/ref-objects.cue
Labels: backport release-1.4

#4387 Fix: fix volumes duplicate in list
  charts/vela-core/templates/defwithtemplate/storage.yaml
  charts/vela-core/templates/defwithtemplate/webservice.yaml
  charts/vela-minimal/templates/defwithtemplate/storage.yaml
  charts/vela-minimal/templates/defwithtemplate/webservice.yaml
  docs/examples/core-definitions/component/webservice.yaml
  docs/examples/core-definitions/trait/storage.yaml
  vela-templates/definitions/internal/component/webservice.cue
  vela-templates/definitions/internal/trait/storage.cue
Labels: backport release-1.4

#4431 Feat: support to init the roles of the user who login by dex
  pkg/apiserver/domain/model/system_info.go
  pkg/apiserver/domain/model/user.go
  pkg/apiserver/domain/service/authentication.go
  pkg/apiserver/domain/service/authentication_test.go
  pkg/apiserver/domain/service/system_info.go
  pkg/apiserver/interfaces/api/dto/v1/types.go
Labels: backport release-1.5

#4429 Fix: support to test authentication with dex
  pkg/apiserver/domain/model/system_info.go
  pkg/apiserver/domain/service/authentication.go
  pkg/apiserver/domain/service/authentication_test.go
  pkg/apiserver/domain/service/user.go
  pkg/apiserver/domain/service/velaql.go
Labels: backport release-1.5

#4433 Fix: address failure when rendering addon API schemas
  pkg/addon/addon.go
  pkg/addon/addon_test.go
  pkg/addon/helper_test.go
  pkg/addon/render.go
  pkg/addon/testdata/example-legacy/Chart.yaml
  pkg/addon/testdata/example-legacy/definitions/dummy.txt
  pkg/addon/testdata/example-legacy/definitions/helm.yaml
  pkg/addon/testdata/example-legacy/metadata.yaml
  pkg/addon/testdata/example-legacy/readme.md
  pkg/addon/testdata/example-legacy/resources/configmap.cue
  pkg/addon/testdata/example-legacy/resources/dummy.txt
  pkg/addon/testdata/example-legacy/resources/parameter.cue
  pkg/addon/testdata/example-legacy/resources/service/source-controller.yaml
  pkg/addon/testdata/example-legacy/template.yaml
  pkg/addon/testdata/example/parameter.cue
  pkg/addon/testdata/example/template.cue
Labels: backport release-1.5

#4450 Revert "Chore: upgrade kind in tests, fix flaky test"
  .github/workflows/apiserver-test.yaml
  .github/workflows/e2e-multicluster-test.yml
  .github/workflows/e2e-rollout-test.yml
  .github/workflows/e2e-test.yml
  .github/workflows/go.yml
  .github/workflows/unit-test.yml
  charts/vela-core/templates/test/test-application.yaml
  makefiles/e2e.mk
  test/e2e-multicluster-test/multicluster_standalone_test.go
  test/e2e-multicluster-test/multicluster_test.go
  test/e2e-multicluster-test/testdata/app/example-envbinding-app.yaml
  test/e2e-multicluster-test/testdata/app/standalone/app-with-publish-version.yaml
  test/e2e-multicluster-test/testdata/app/standalone/app.yaml
  test/e2e-multicluster-test/testdata/app/standalone/deployment.yaml
  test/e2e-multicluster-test/testdata/app/standalone/policy-zero-replica.yaml
  test/e2e-multicluster-test/testdata/app/standalone/policy.yaml
  test/e2e-multicluster-test/testdata/app/standalone/workflow-suspend.yaml
  test/e2e-multicluster-test/testdata/app/standalone/workflow.yaml
  test/e2e-test/app_resourcetracker_test.go
  test/e2e-test/application_test.go
  test/e2e-test/health_scope_test.go
  test/e2e-test/resource_policy_test.go
  test/e2e-test/suite_test.go
  test/e2e-test/testdata/app/app1.yaml
  test/e2e-test/testdata/app/app2.yaml
  test/e2e-test/testdata/app/app3.yaml
  test/e2e-test/testdata/app/app4.yaml
  test/e2e-test/testdata/app/app6.yaml
  test/e2e-test/testdata/app/app7.yaml
  test/e2e-test/testdata/app/app_healthscope.yaml
  test/e2e-test/testdata/app/app_healthscope_unhealthy.yaml
  test/e2e-test/testdata/app/app_suspending.yaml
  test/e2e-test/testdata/app/app_wait_suspend.yaml
  test/e2e-test/testdata/rollout/cloneset/app-remove-ingress.yaml
  test/e2e-test/testdata/rollout/cloneset/app-with-ingress-source.yaml
  test/e2e-test/testdata/rollout/cloneset/app-with-ingress-target.yaml
Labels: title-needs-formatting, backport release-1.5

#4447 Fix: the history applications are repeatedly synchronized
  pkg/apiserver/event/sync/cache.go
  pkg/apiserver/event/sync/cr2ux.go
Labels: backport release-1.5

#4439 Feat: adapt vela port-forward with the velaql
  Dockerfile.cli
  pkg/utils/common/common.go
  pkg/velaql/providers/query/types/type.go
  references/cli/portforward.go
  references/cli/status.go
  references/cli/utils.go
  references/cli/velaql.go
  references/cli/velaql_test.go
  references/common/application.go
  references/docgen/def-doc/trait/service-account.eg.md
  references/docgen/parser.go
Labels: area/cli, backport release-1.5

#4441 Feat: support to query the alias of the project member
  pkg/apiserver/domain/service/project.go
  pkg/apiserver/domain/service/project_test.go
  pkg/apiserver/interfaces/api/dto/v1/types.go
  test/e2e-test/resource_policy_test.go
Labels: backport release-1.5

#4444 Feat: support outputs for addon
  pkg/addon/addon.go
  pkg/addon/render.go
  pkg/addon/render_test.go
  pkg/addon/utils.go
Labels: backport release-1.5

#4446 Feat: add featuregates to disallow url in ref-objects
  pkg/appfile/parser.go
  pkg/features/controller_features.go
Labels: backport release-1.4, backport release-1.5

#4443 Feat: support vela addon enable with package
  pkg/addon/addon.go
  pkg/addon/render.go
  pkg/addon/render_test.go
  pkg/cue/model/value/value.go
Labels: backport release-1.5

#4455 Fix: The apply failure error is ignored when the workflow is executed
  pkg/workflow/providers/kube/handle.go
Labels: backport release-1.2, backport release-1.3, backport release-1.4, backport release-1.5

#4448 Feat: delete svc flag from vela delete cli cmd
  references/cli/common.go
  references/cli/delete.go
Labels: backport release-1.5

#4464 Fix: docker file fail to build for vela cli
  Dockerfile.cli
  references/docgen/def-doc/trait/service-account.eg.md
Labels: backport release-1.5

#4467 Chore: refactor addon enable with package
  pkg/addon/addon.go
  pkg/addon/addon_suite_test.go
  pkg/addon/addon_test.go
  pkg/addon/helper.go
  pkg/addon/init.go
  pkg/addon/render.go
  pkg/addon/render_test.go
  pkg/cue/model/value/value.go
  pkg/oam/labels.go
Labels: backport release-1.5

#4471 Fix: fix logs to record the right publish version
  pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go
Labels: backport release-1.2, backport release-1.3, backport release-1.4, backport release-1.5

#4473 Fix: address vela-core crash due to empty policy properties
  pkg/policy/common_test.go
  pkg/policy/envbinding/utils.go
  pkg/policy/override.go
  pkg/policy/override_test.go
  pkg/policy/topology.go
  pkg/policy/topology_test.go
  pkg/resourcekeeper/gc.go
  pkg/workflow/providers/multicluster/deploy.go
  pkg/workflow/providers/multicluster/deploy_test.go
Labels: backport release-1.3, backport release-1.4, backport release-1.5

#4484 Feat: delete multi apps from vela delete cli command
  references/cli/delete.go
  references/common/application.go
Labels: backport release-1.5

#4492 Fix: repeat query configuration type
  pkg/apiserver/domain/service/config.go
Labels: backport release-1.5

#4379 Feat: System Info & Diagnose
  references/cli/cli.go
  references/cli/system.go
Labels: backport release-1.5

#4493 Fix: check definition of addon whether is conflict
  pkg/addon/addon.go
  pkg/addon/addon_suite_test.go
  pkg/addon/addon_test.go
  pkg/addon/utils.go
  pkg/addon/utils_test.go
  references/cli/addon.go
Labels: backport release-1.5

#4495 Fix: CloudShell read-only authorization is not automatically revoked
  pkg/apiserver/domain/service/cloudshell.go
  pkg/apiserver/domain/service/cloudshell_test.go
  pkg/apiserver/domain/service/rbac.go
  pkg/apiserver/interfaces/api/cloudshell.go
  pkg/apiserver/utils/auth.go
  pkg/auth/privileges.go
Labels: backport release-1.5

#4491 Fix: failed to assign the default role for the users who log in from dex
  pkg/apiserver/domain/model/system_info.go
  pkg/apiserver/domain/service/authentication.go
  pkg/apiserver/domain/service/authentication_test.go
  pkg/apiserver/domain/service/system_info.go
  pkg/apiserver/interfaces/api/dto/v1/types.go
  pkg/multicluster/cluster_management.go
  test/e2e-apiserver-test/suite_test.go
Labels: backport release-1.5

#4422 Feat: support set labels for env
  apis/types/types.go
  pkg/utils/env/env.go
  references/cli/env.go
Labels: backport release-1.5
