Repository kubevela/kubevela, pull requests merged in 2022-10, with the labels that each got.

#4831 Fix: fix addon render cue template cross-file reference bug
  pkg/addon/render.go
  pkg/addon/render_test.go
Labels: backport release-1.5

#4833 Chore: add IP for gateway trait
  charts/vela-core/templates/defwithtemplate/gateway.yaml
  charts/vela-minimal/templates/defwithtemplate/gateway.yaml
  vela-templates/definitions/internal/trait/gateway.cue
Labels: backport release-1.5

#4830 Fix: align sha256sums file with binary name
  .github/workflows/release.yml
Labels: backport release-1.5

#4850 Fix: change LabelResourceRuleFormat from Annotations to Labels
  pkg/velaql/providers/query/tree.go
  pkg/velaql/providers/query/tree_test.go
Labels: backport release-1.5

#4857 Fix: support default value of ui schema
  pkg/apiserver/utils/ui_schema.go
Labels: backport release-1.4, backport release-1.5

#4852 Fix: prevent rerun app while upgrade due to old apprev lack app workflow
  pkg/controller/core.oam.dev/v1alpha2/application/revision.go
  pkg/controller/core.oam.dev/v1alpha2/application/revision_test.go
Labels: backport release-1.5

#4894 Chore: change the package name of the readme-generator-for-helm
  makefiles/dependency.mk
Labels: backport release-1.4, backport release-1.5

#4902 Chore: wrong endpoint for LoadBalancer type service(revert #4729)
  pkg/velaql/providers/query/endpoint.go
  pkg/velaql/providers/query/endpoint_test.go
  pkg/velaql/providers/query/handler_test.go
  references/cli/velaql_test.go
Labels: backport release-1.5

#4915 Fix: add sub step in vela workflow logs
  references/cli/debug.go
  references/cli/workflow.go
Labels: backport release-1.6

#4874 Feat: enhance the apply-once capability
  apis/core.oam.dev/v1alpha1/applyonce_types.go
  charts/vela-core/templates/defwithtemplate/apply-once.yaml
  charts/vela-minimal/templates/defwithtemplate/apply-once.yaml
  docs/examples/app-with-policy/apply-once-policy/apply-once.md
  pkg/controller/core.oam.dev/v1alpha2/application/apply_once_policy_test.go
  pkg/resourcekeeper/dispatch.go
  pkg/resourcekeeper/statekeep.go
  vela-templates/definitions/internal/policy/apply-once.cue
Labels: backport release-1.6

#4920 Feat: support operations for workflow run
  go.mod
  go.sum
  pkg/apiserver/domain/service/workflow.go
  pkg/workflow/operation/operation.go
  pkg/workflow/operation/operation_test.go
  references/cli/workflow.go
  references/cli/workflow_test.go
Labels: backport release-1.6

#4925 Fix: can't get pods of CronTask component
  charts/vela-core/templates/defwithtemplate/cron-task.yaml
  charts/vela-minimal/templates/defwithtemplate/cron-task.yaml
  pkg/velaql/providers/query/tree.go
  pkg/velaql/providers/query/tree_test.go
  vela-templates/definitions/internal/component/cron-task.cue
Labels: backport release-1.6

#4923 Fix: get Application status using jsonpath filter expression
  references/cli/utils.go
  references/cli/utils_test.go
Labels: backport release-1.6

#4935 Fix: fix gen doc for container image
  references/docgen/cluster.go
  references/docgen/fix/fix.go
  references/docgen/parser.go
Labels: backport release-1.6

#4934 Fix: fix use gitlab repo as addon registry
  references/cli/addon-registry.go
Labels: backport release-1.5, backport release-1.6

#4932 Fix: update export2config and export2secret example
  references/docgen/def-doc/workflowstep/export2config.eg.md
  references/docgen/def-doc/workflowstep/export2secret.eg.md
Labels: backport release-1.6

#4942 Fix: can't obtain pods generated by `Crontask` component (patch of PR 4925)
  charts/vela-core/templates/defwithtemplate/cron-task.yaml
  charts/vela-minimal/templates/defwithtemplate/cron-task.yaml
  pkg/velaql/providers/query/suite_test.go
  pkg/velaql/providers/query/tree.go
  pkg/velaql/providers/query/tree_test.go
  vela-templates/definitions/internal/component/cron-task.cue
Labels: backport release-1.6

#4916 Fix: apiserver & vela status use multi-cluster client
  pkg/apiserver/infrastructure/clients/kubeclient.go
  pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go
  pkg/multicluster/utils.go
  pkg/utils/common/args.go
  references/cli/cluster.go
  references/cli/status.go
  references/cli/velaql.go
Labels: backport release-1.6

#4927 Fix: explicit error info for enabling addon with velaux
  e2e/addon/mock/testdata/not-match-addon/metadata.yaml
  pkg/apiserver/domain/service/addon.go
  test/e2e-apiserver-test/addon_test.go
Labels: backport release-1.6

#4936 Feat: sync the model of api workflow with core
  pkg/apiserver/domain/model/workflow.go
  pkg/apiserver/domain/repository/workflow.go
  pkg/apiserver/domain/repository/workflow_test.go
  pkg/apiserver/domain/service/application_test.go
  pkg/apiserver/domain/service/rbac.go
  pkg/apiserver/domain/service/workflow.go
  pkg/apiserver/domain/service/workflow_test.go
  pkg/apiserver/event/sync/convert/convert.go
  pkg/apiserver/interfaces/api/assembler/v1/do2dto.go
  pkg/apiserver/interfaces/api/assembler/v1/dto2do.go
  pkg/apiserver/interfaces/api/dto/v1/types.go
Labels: backport release-1.6

#4944 Fix: delete redundant null pointer operation
  pkg/apiserver/infrastructure/datastore/mongodb/mongodb.go
Labels: backport release-1.6

#4947 Fix: update namespace only if it doesn't have the env label
  pkg/utils/k8s.go
Labels: backport release-1.6

#4951 Fix: bocde error override origin error message
  pkg/apiserver/domain/service/addon.go
Labels: backport release-1.6

#4926 Feat: add mode in workflow template
  charts/vela-core/crds/core.oam.dev_applicationrevisions.yaml
  charts/vela-core/crds/core.oam.dev_applications.yaml
  charts/vela-core/crds/core.oam.dev_workflows.yaml
  charts/vela-minimal/crds/core.oam.dev_applicationrevisions.yaml
  charts/vela-minimal/crds/core.oam.dev_applications.yaml
  go.mod
  go.sum
  legacy/charts/vela-core-legacy/crds/core.oam.dev_applicationrevisions.yaml
  legacy/charts/vela-core-legacy/crds/core.oam.dev_applications.yaml
  legacy/charts/vela-core-legacy/crds/core.oam.dev_workflows.yaml
  pkg/appfile/parser.go
  pkg/stdlib/pkgs/oam.cue
  test/e2e-multicluster-test/multicluster_standalone_test.go
  test/e2e-multicluster-test/testdata/app/standalone/workflow.yaml
Labels: backport release-1.6

#4954 Fix: do not change the workflow after the env changed
  pkg/apiserver/domain/service/application_test.go
  pkg/apiserver/domain/service/env.go
  pkg/apiserver/domain/service/env_test.go
  pkg/apiserver/utils/bcode/011_env.go
Labels: backport release-1.6

#4963 Chore: stable the version of cue and workflow
  go.mod
  go.sum
  pkg/controller/core.oam.dev/v1alpha2/application/application_controller_test.go
  pkg/workflow/workflow.go
Labels: backport release-1.6

#4908 Feat: implement pipeline APIs
  .github/workflows/apiserver-test.yaml
  docs/apidoc/swagger.json
  e2e/addon/mock/testrepo/helm-repo/index.yaml
  e2e/addon/mock/testrepo/helm-repo/vela-workflow-v0.3.1.tgz
  e2e/addon/mock/vela_addon_mock_server.go
  go.mod
  pkg/addon/addon.go
  pkg/apiserver/domain/model/pipeline.go
  pkg/apiserver/domain/model/project.go
  pkg/apiserver/domain/service/cloudshell_test.go
  pkg/apiserver/domain/service/helm_test.go
  pkg/apiserver/domain/service/pipeline.go
  pkg/apiserver/domain/service/pipeline_test.go
  pkg/apiserver/domain/service/project.go
  pkg/apiserver/domain/service/rbac.go
  pkg/apiserver/domain/service/rbac_test.go
  pkg/apiserver/domain/service/suite_test.go
  pkg/apiserver/domain/service/workflow_test.go
  pkg/apiserver/infrastructure/clients/kubeclient.go
  pkg/apiserver/interfaces/api/dto/v1/types.go
  pkg/apiserver/interfaces/api/interfaces.go
  pkg/apiserver/interfaces/api/pipeline.go
  pkg/apiserver/interfaces/api/project.go
  pkg/apiserver/utils/bcode/017_pipeline.go
  pkg/utils/k8s.go
  references/cli/logs.go
  test/e2e-apiserver-test/pipeline_test.go
  test/e2e-apiserver-test/suite_test.go
  test/e2e-apiserver-test/testdata/log.yaml
  test/e2e-apiserver-test/testdata/request.yaml
Labels: backport release-1.6
