Repository kubevela/kubevela, pull requests merged in 2023-01, with the labels that each got.

#5246 Fix: dry run from revision application patch error
  pkg/apiserver/domain/service/application.go
Labels: backport release-1.5, backport release-1.6

#5275 Fix: apiserver k8sclient have duplicated multicluster wrapper
  go.mod
  go.sum
  pkg/velaql/providers/query/handler.go
Labels: backport release-1.6

#5276 Fix: keep the workflow data structure in MongoDB
  pkg/apiserver/domain/model/workflow.go
Labels: backport release-1.6

#5286 Test: use mock server in addon tests
  pkg/addon/helper_test.go
Labels: backport release-1.6, backport release-1.7

#5287 Fix: delete appplication fails if status.workflow.endTime not specified.
  apis/core.oam.dev/common/types.go
  charts/vela-core/crds/core.oam.dev_applicationrevisions.yaml
  charts/vela-core/crds/core.oam.dev_applications.yaml
  charts/vela-minimal/crds/core.oam.dev_applicationrevisions.yaml
  charts/vela-minimal/crds/core.oam.dev_applications.yaml
  legacy/charts/vela-core-legacy/crds/core.oam.dev_applicationrevisions.yaml
  legacy/charts/vela-core-legacy/crds/core.oam.dev_applications.yaml
Labels: backport release-1.5, backport release-1.6, backport release-1.7

#5295 Fix: don't return err if subresource type is not found when listing application resources.
  pkg/velaql/providers/query/tree.go
Labels: backport release-1.6, backport release-1.7

#5298 Fix: more explicit error when addon package hasn't a metadata.yaml
  pkg/addon/addon.go
  pkg/addon/helper.go
  pkg/addon/utils.go
  pkg/addon/utils_test.go
  references/cli/addon.go
Labels: backport release-1.6, backport release-1.7

#5274 Fix: Index structure map[string]string,Mongo resulting in inconsistent results obtained by filtering non-string type by index.
  pkg/apiserver/domain/model/application.go
  pkg/apiserver/domain/model/cluster.go
  pkg/apiserver/domain/model/env.go
  pkg/apiserver/domain/model/envbinding.go
  pkg/apiserver/domain/model/pipeline.go
  pkg/apiserver/domain/model/project.go
  pkg/apiserver/domain/model/system_info.go
  pkg/apiserver/domain/model/target.go
  pkg/apiserver/domain/model/user.go
  pkg/apiserver/domain/model/workflow.go
  pkg/apiserver/domain/service/workflow.go
  pkg/apiserver/infrastructure/datastore/datastore.go
  pkg/apiserver/infrastructure/datastore/kubeapi/kubeapi.go
  pkg/apiserver/infrastructure/datastore/kubeapi/kubeapi_test.go
  pkg/utils/strings.go
  pkg/utils/strings_test.go
Labels: backport release-1.7

#4815 Feat: vela dry-run render results should be affected by override policy and deploy workflowstep
  pkg/appfile/dryrun/diff_test.go
  pkg/appfile/dryrun/dryrun.go
  pkg/appfile/dryrun/dryrun_test.go
  pkg/appfile/dryrun/suit_test.go
  pkg/appfile/dryrun/testdata/pd-mypolicy.yaml
  pkg/appfile/dryrun/testdata/testing-dry-run-1.yaml
  pkg/appfile/dryrun/testdata/testing-dry-run-2.yaml
  pkg/appfile/dryrun/testdata/testing-dry-run-3.yaml
  pkg/appfile/dryrun/testdata/testing-dry-run-4.yaml
  pkg/appfile/dryrun/testdata/testing-dry-run-5.yaml
  references/cli/dryrun.go
  references/cli/dryrun_test.go
  references/cli/livediff.go
  references/cli/test-data/dry-run/app.yaml
  references/cli/test-data/dry-run/my-comp.cue
  references/cli/test-data/dry-run/testing-dry-run-1.yaml
  references/cli/test-data/dry-run/testing-dry-run-2.yaml
  references/cli/test-data/dry-run/testing-dry-run-3.yaml
  references/cli/test-data/dry-run/testing-dry-run-4.yaml
  references/cli/test-data/dry-run/testing-dry-run-5.yaml
  references/cli/test-data/dry-run/testing-dry-run-6.yaml
  references/cli/test-data/dry-run/testing-policy.yaml
  references/cli/test-data/dry-run/testing-trait.yaml
  references/cli/test-data/dry-run/testing-wf.yaml
  references/cli/test-data/dry-run/testing-worker-def.yaml
Labels: backport release-1.7

#5299 Feat: enhance the application synchronizer
  pkg/addon/addon.go
  pkg/apiserver/domain/model/whole.go
  pkg/apiserver/domain/repository/suite_test.go
  pkg/apiserver/domain/service/suite_test.go
  pkg/apiserver/event/collect/suit_test.go
  pkg/apiserver/event/collect/system_info_collect.go
  pkg/apiserver/event/collect/system_info_collect_test.go
  pkg/apiserver/event/sync/cache.go
  pkg/apiserver/event/sync/cache_test.go
  pkg/apiserver/event/sync/convert.go
  pkg/apiserver/event/sync/cr2ux.go
  pkg/apiserver/event/sync/cr2ux_test.go
  pkg/apiserver/event/sync/suit_test.go
  pkg/apiserver/event/sync/worker.go
  pkg/apiserver/event/sync/worker_test.go
  pkg/apiserver/infrastructure/datastore/kubeapi/kubeapi.go
  pkg/apiserver/infrastructure/datastore/kubeapi/kubeapi_suite_test.go
  pkg/apiserver/infrastructure/datastore/kubeapi/migrate.go
  pkg/apiserver/infrastructure/datastore/kubeapi/migrate_test.go
  pkg/apiserver/interfaces/api/api_suite_test.go
  pkg/apiserver/interfaces/api/target.go
  pkg/apiserver/server.go
  pkg/apiserver/utils/auth.go
  pkg/auth/round_trippers.go
  test/e2e-apiserver-test/application_sync_test.go
Labels: backport release-1.7

#5270 Fix: create a config with the same name reported an incorrect error
  pkg/apiserver/domain/service/config.go
  pkg/apiserver/utils/bcode/016_config.go
  pkg/config/factory.go
  pkg/config/factory_test.go
  test/e2e-apiserver-test/config_test.go
Labels: backport release-1.6, backport release-1.7

#5304 Fix: error msg when uninstall vela
  references/cli/uninstall.go
Labels: backport release-1.6, backport release-1.7

#5316 Fix: fix error info when there is no note.cue and optimize addon init command
  pkg/addon/addon.go
  pkg/addon/init.go
  references/cli/addon.go
Labels: backport release-1.7

#5317 Fix: the developer user can't load the definition
  pkg/apiserver/domain/service/application.go
  pkg/apiserver/server.go
  pkg/appfile/dryrun/dryrun.go
  pkg/velaql/providers/query/handler.go
Labels: backport release-1.7

#5321 Fix: correct typo in the long cli description of vela system command
  references/cli/system.go
Labels: backport release-1.7

#5320 Feat: velaql support indexing into exported array field
  pkg/velaql/parse.go
  pkg/velaql/parse_test.go
Labels: backport release-1.7

#5257 Feat: need one Trait to set Rollout strategy of Workload
  charts/vela-core/templates/defwithtemplate/k8s-update-strategy.yaml
  references/docgen/def-doc/trait/k8s-update-strategy.eg.md
  vela-templates/definitions/internal/trait/k8s-update-strategy.cue
  vela-templates/definitions/usage-examples/application-daemon-with-k8s-update-strategy.yaml
  vela-templates/definitions/usage-examples/application-with-k8s-update-strategy.yaml
Labels: backport release-1.7

#5328 Fix: maintain compatibility with old project data
  pkg/apiserver/domain/service/workflow.go
  pkg/apiserver/event/sync/convert.go
Labels: backport release-1.7

#5330 Fix: conflict while using gc policy and shared-resource policy concurrently
  .github/workflows/apiserver-test.yml
  .github/workflows/unit-test.yml
  charts/vela-minimal/templates/defwithtemplate/k8s-update-strategy.yaml
  pkg/resourcekeeper/gc.go
  test/e2e-multicluster-test/multicluster_test.go
  test/e2e-multicluster-test/testdata/app/app-gc-shared.yaml
Labels: backport release-1.6, backport release-1.7

#5335 Feat: upgrade the workflow version to v0.4.0
  go.mod
  go.sum
Labels: backport release-1.7

#5334 Fix: optimize skip reconcile and expose error if the traits patch an invalid workload like terraform
  pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go
  pkg/cue/definition/template.go
  pkg/cue/definition/template_test.go
Labels: backport release-1.6, backport release-1.7

#5332 Fix: the --cluster not work when enable addon
  references/cli/addon.go
  references/cli/addon_test.go
Labels: backport release-1.5, backport release-1.6, backport release-1.7

#5354 Feat: upgrade cluster gateway to 1.7.0
  charts/vela-core/README.md
  charts/vela-core/values.yaml
  charts/vela-minimal/README.md
  charts/vela-minimal/values.yaml
Labels: backport release-1.7

#5329 Fix: fix panic if trait tries to patch an invalid workload like terraform
  pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go
  pkg/cue/definition/template.go
  pkg/cue/definition/template_test.go
  pkg/workflow/workflow.go
Labels: backport release-1.2, backport release-1.3, backport release-1.4

#5377 Fix: failed to create the record when rollbacking the application
  pkg/apiserver/domain/service/application.go
Labels: backport release-1.7

#5383 Chore: update workflow version to fix panic
  go.mod
  go.sum
Labels: backport release-1.7

#5385 Fix: rework on apisrever e2e test covergae
  .github/workflows/apiserver-test.yml
Labels: backport release-1.7

#5384 Fix: aligin config create to be managed by apps with Dispatch function
  cmd/core/app/options/options.go
  pkg/config/factory.go
  pkg/config/provider/provider.go
  pkg/config/provider/provider_test.go
  pkg/controller/core.oam.dev/v1alpha2/application/generator.go
  pkg/utils/apply/apply.go
  pkg/utils/apply/apply_test.go
  references/cli/delete.go
Labels: backport release-1.7

#5382 Feat: add the updating the application trigger API
  docs/apidoc/swagger.json
  pkg/apiserver/domain/service/application.go
  pkg/apiserver/domain/service/application_test.go
  pkg/apiserver/domain/service/webhook_test.go
  pkg/apiserver/domain/service/workflow_test.go
  pkg/apiserver/interfaces/api/application.go
  pkg/apiserver/interfaces/api/assembler/v1/do2dto.go
  pkg/apiserver/interfaces/api/dto/v1/types.go
  test/e2e-apiserver-test/application_test.go
Labels: backport release-1.7

#5379 Fix: use the namespace specified in the resource if -n is not s…
  references/cli/adopt.go
  references/cli/adopt_test.go
Labels: backport release-1.7
