Repository kubevela/kubevela, pull requests merged in 2023-05, with the labels that each got.

#5950 Fix: trait not added in Go SDK
  pkg/definition/gen_sdk/go.go
Labels: backport release-1.8

#5638 Chore: Give the help information of Makefile to make it more clear
  Makefile
  pkg/addon/addon_suite_test.go
  pkg/addon/init.go
  pkg/addon/memory_reader_test.go
  pkg/addon/utils.go
Labels: lgtm, triage/accepted

#5968 Feat: provider doc generator
  go.mod
  references/cuegen/generators/provider/testdata/valid.md
  references/docgen/provider.go
  references/docgen/provider_test.go
Labels: lgtm, triage/accepted

#5860 Feat: Add support for multiple gateway traits
  charts/vela-core/README.md
  charts/vela-core/templates/defwithtemplate/gateway.yaml
  vela-templates/definitions/internal/trait/gateway.cue
Labels: lgtm, triage/accepted

#5958 Feat: only print to stdout
  go.mod
  references/cli/def.go
  references/cli/def_test.go
Labels: lgtm, triage/accepted

#5982 Fix: fix the typo error in vela top
  references/cli/top/component/menu.go
  references/cli/top/view/application_view.go
Labels: backport release-1.8

#5987 Chore: CUE code quality changes
  charts/vela-core/templates/defwithtemplate/apply-terraform-config.yaml
  charts/vela-core/templates/defwithtemplate/expose.yaml
  charts/vela-core/templates/defwithtemplate/topologyspreadconstraints.yaml
  vela-templates/definitions/internal/trait/expose.cue
  vela-templates/definitions/internal/trait/topologyspreadconstraints.cue
  vela-templates/definitions/internal/workflowstep/apply-terraform-config.cue
Labels: needs-format, triage/accepted

#5739 Feat: application_controller should be responsible for deleting application revision
  pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go
  pkg/controller/core.oam.dev/v1alpha2/application/apply.go
  pkg/controller/core.oam.dev/v1alpha2/application/revision.go
  pkg/resourcekeeper/gc.go
  pkg/resourcekeeper/gc_rev.go
  pkg/resourcekeeper/gc_rev_test.go
  pkg/resourcekeeper/options.go
Labels: triage/accepted
