Repository kubevela/kubevela, pull requests merged in 2023-03, with the labels that each got.

#5578 Fix: the array type cannot be converted to interface type
  pkg/apiserver/domain/service/util.go
  pkg/apiserver/domain/service/util_test.go
Labels: backport release-1.7

#5547 Fix: length of name should be less than 32
  pkg/apiserver/interfaces/api/validate.go
  test/e2e-apiserver-test/suite_test.go
Labels: backport release-1.6, backport release-1.7

#5615 Fix: replication example componentdefinition miss workload field for …
  references/docgen/def-doc/policy/replication.eg.md
  test/e2e-test/testdata/definition/replica-webservice.yaml
Labels: backport release-1.6, backport release-1.7

#5614 Fix: make read-only object not found error more clear
  pkg/utils/apply/apply.go
Labels: backport release-1.7

#5604 Fix: stores workflow status in revison if it is restarted
  pkg/controller/core.oam.dev/v1alpha2/application/application_controller.go
  pkg/controller/core.oam.dev/v1alpha2/application/application_controller_test.go
  pkg/controller/core.oam.dev/v1alpha2/application/generator.go
  pkg/controller/core.oam.dev/v1alpha2/application/generator_test.go
  pkg/controller/core.oam.dev/v1alpha2/application/revision.go
Labels: backport release-1.6, backport release-1.7

#5646 Fix: add addon registry
  references/cli/addon-registry.go
Labels: backport release-1.7

#5658 Fix: cve-2022-4203
  Dockerfile
Labels: backport release-1.7

#5657 Fix: vulnerability CVE-2023-27483
  go.mod
  go.sum
Labels: backport release-1.7

#5579 Fix: parameter type is conflict with Component webserice and Trait re…
  charts/vela-core/templates/defwithtemplate/resource.yaml
  charts/vela-minimal/templates/defwithtemplate/resource.yaml
  pkg/definition/gen_sdk/testdata/one_of.cue
  vela-templates/definitions/internal/trait/resource.cue
  vela-templates/definitions/usage-examples/application-with-resource.yaml
Labels: backport release-1.6, backport release-1.7

#5690 Feat: add adopt all command
  charts/vela-core/templates/defwithtemplate/storage.yaml
  charts/vela-minimal/templates/defwithtemplate/storage.yaml
  go.mod
  go.sum
  references/cli/adopt.go
  references/cli/adopt_test.go
  references/cli/resource-topology/builtin-rule.cue
  vela-templates/definitions/internal/trait/storage.cue
Labels: backport release-1.7

#5709 Fix: system crd validation hook should not always use the default vel…
  cmd/core/app/hooks/pre_start_hook.go
Labels: backport release-1.7

#5705 Fix: use logs to show errs instead of returning in adopt all
  references/cli/adopt.go
Labels: backport release-1.7

#5728 Feat: enhance vela adopt and refactor
  references/cli/adopt-templates/default.cue
  references/cli/adopt.go
  test/e2e-multicluster-test/multicluster_test.go
Labels: backport release-1.8

#5741 Feat: fix flaky multicluster test
  test/e2e-multicluster-test/multicluster_test.go
Labels: backport release-1.8

#5745 Fix: vela top cannot set theme
  references/cli/top/config/color.go
  references/cli/top/config/color_test.go
Labels: backport release-1.7, backport release-1.8

#5759 Chore: stable the version of workflow to 0.5.0 for 1.8 release
  go.mod
  go.sum
Labels: backport release-1.8

#5768 Feat: add check prometheus metrics workflowStepDefinition
  charts/vela-core/templates/defwithtemplate/check-metrics.yaml
  charts/vela-minimal/templates/defwithtemplate/check-metrics.yaml
  references/docgen/def-doc/workflowstep/check-metrics.eg.md
  vela-templates/definitions/internal/workflowstep/check-metrics.cue
Labels: backport release-1.8

#5781 Feat: expose trait with new ports
  charts/vela-core/templates/defwithtemplate/expose.yaml
  charts/vela-minimal/templates/defwithtemplate/expose.yaml
  vela-templates/definitions/internal/trait/expose.cue
Labels: backport release-1.8
