Repository kubevela/kubevela, pull requests merged in 2023-04, with the labels that each got.

#5783 Fix: filter rollout created by rolling-release in `vela workflow resume`
  pkg/oam/labels.go
  pkg/rollout/rollout.go
  pkg/rollout/rollout_test.go
Labels: backport release-1.8

#5799 Feat: add mode in steps for step group
  charts/vela-core/crds/core.oam.dev_applicationrevisions.yaml
  charts/vela-core/crds/core.oam.dev_applications.yaml
  charts/vela-minimal/crds/core.oam.dev_applicationrevisions.yaml
  charts/vela-minimal/crds/core.oam.dev_applications.yaml
  go.mod
  go.sum
  legacy/charts/vela-core-legacy/crds/core.oam.dev_applicationrevisions.yaml
  legacy/charts/vela-core-legacy/crds/core.oam.dev_applications.yaml
  pkg/controller/core.oam.dev/v1alpha2/application/application_controller_test.go
Labels: backport release-1.8

#5800 Feat: compatibility on componentDefinition spec.workload.definition field
  apis/types/capability.go
  charts/vela-core/templates/defwithtemplate/cron-task.yaml
  charts/vela-minimal/templates/defwithtemplate/cron-task.yaml
  pkg/oam/util/helper.go
  pkg/oam/util/helper_test.go
  references/common/registry.go
  references/docgen/cluster.go
  vela-templates/definitions/internal/component/cron-task.cue
Labels: backport release-1.8

#5805 Fix: fix step id to name in workflow logs
  references/cli/logs.go
  references/cli/workflow.go
Labels: backport release-1.7, backport release-1.8

#5809 Fix: use step id to filter the log data and fix the regex
  references/cli/logs.go
  references/cli/workflow.go
Labels: backport release-1.7, backport release-1.8

#5206 Refactor: the addon dependency installation logic is accurate to the cluster
  e2e/addon/addon_test.go
  e2e/addon/mock/testdata/mock-dependence-rely/README.md
  e2e/addon/mock/testdata/mock-dependence-rely/definitions/mytraitb.cue
  e2e/addon/mock/testdata/mock-dependence-rely/metadata.yaml
  e2e/addon/mock/testdata/mock-dependence-rely/parameter.cue
  e2e/addon/mock/testdata/mock-dependence-rely/resources/myresourceb.cue
  e2e/addon/mock/testdata/mock-dependence-rely/template.cue
  e2e/addon/mock/testdata/mock-dependence/README.md
  e2e/addon/mock/testdata/mock-dependence/definitions/mytrait.cue
  e2e/addon/mock/testdata/mock-dependence/metadata.yaml
  e2e/addon/mock/testdata/mock-dependence/parameter.cue
  e2e/addon/mock/testdata/mock-dependence/resources/myresource-depend.cue
  e2e/addon/mock/testdata/mock-dependence/template.cue
  pkg/addon/addon.go
  pkg/addon/addon_suite_test.go
Labels: backport release-1.8

#5834 Fix: fix multi clusters bottom in vela adopt
  references/cli/adopt-templates/default.cue
  references/cli/adopt.go
  references/cli/resource-topology/builtin-rule.cue
Labels: backport release-1.8

#5845 Feat: add new fields for addon metadata
  pkg/addon/type.go
  pkg/utils/common/common.go
Labels: backport release-1.8

#5856 Fix: fix bug when dependency addon parameter is Empty
  pkg/addon/addon.go
Labels: backport release-1.8

#5872 Fix: fix terminate suspending steps
  pkg/workflow/operation/operation.go
  pkg/workflow/operation/operation_test.go
Labels: backport release-1.8

#5848 Feat: support parse template depends on CueX
  pkg/config/factory.go
  pkg/config/writer/nacos.go
  pkg/config/writer/writer.go
  pkg/cue/cuex/providers/config/config.cue
  pkg/cue/cuex/providers/config/config.go
  pkg/cue/script/schema.go
  pkg/cue/script/template.go
  pkg/cue/script/template_test.go
  pkg/utils/common/common.go
  pkg/utils/common/common_test.go
Labels: triage/accepted

#5894 Feat: support validate properties with CueX
  pkg/config/factory.go
  pkg/cue/script/template.go
  pkg/cue/script/template_test.go
Labels: triage/accepted

#5893 Fix: make any as top value in cue
  references/cuegen/README.md
  references/cuegen/convert.go
  references/cuegen/convert_test.go
  references/cuegen/generator_test.go
  references/cuegen/option.go
  references/cuegen/option_test.go
  references/cuegen/testdata/valid.cue
  references/cuegen/util.go
  references/cuegen/util_test.go
Labels: triage/accepted

#5901 Fix: multi cluster inline policy load extra definitions
  pkg/appfile/template.go
  test/e2e-multicluster-test/multicluster_test.go
  test/e2e-multicluster-test/testdata/app/app-carrying-deploy-step-with-inline-policy.yaml
  test/e2e-multicluster-test/testdata/def/inline-deploy.yaml
Labels: backport release-1.8

#5786 Fix: support get helm chart values from which index.yaml urls is not …
  pkg/utils/helm/helm_helper.go
  pkg/utils/helm/helm_helper_test.go
  pkg/utils/helm/testdata/index.yaml
Labels: triage/accepted

#5922 Fix: multicluster disable installation
  charts/vela-core/templates/kubevela-controller.yaml
Labels: backport release-1.8

#5865 Fix: install dependency is invalid for runtime addon when it's cluster arg is nil
  e2e/addon/addon_test.go
  e2e/addon/mock/testdata/mock-dependence-rely2/README.md
  e2e/addon/mock/testdata/mock-dependence-rely2/metadata.yaml
  e2e/addon/mock/testdata/mock-dependence-rely2/parameter.cue
  e2e/addon/mock/testdata/mock-dependence-rely2/template.cue
  e2e/addon/mock/testdata/mock-dependence2/README.md
  e2e/addon/mock/testdata/mock-dependence2/metadata.yaml
  e2e/addon/mock/testdata/mock-dependence2/parameter.cue
  e2e/addon/mock/testdata/mock-dependence2/template.cue
  pkg/addon/addon.go
  pkg/addon/addon_suite_test.go
Labels: backport release-1.8
